name = "r2-image-host"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "IMG_BUCKET"
bucket_name = "img-bucket"

[placement]
mode = "smart"
